name: MLOps CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  train-and-evaluate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python src/train.py

      - name: Verify trained model
        run: |
          ls -lh model/
          test -f model/model.joblib

      - name: Evaluate model
        run: |
          python src/evaluate.py

      - name: Test SageMaker inference
        run: |
          python tests/test_sagemaker_inference.py

      - name: Prepare SageMaker inference code
        run: |
          mkdir -p model/code
          cp src/sagemaker_inference.py model/code/inference.py

      - name: Package SageMaker model
        run: |
          tar -czf model/model.tar.gz -C model model.joblib code

      - name: Verify SageMaker model package
        run: |
          ls -lh model/
          echo "Contents of model.tar.gz:"
          tar -tzf model/model.tar.gz

      - name: Upload MLOps artifacts
        uses: actions/upload-artifact@v4
        with:
          name: churn-model-artifacts
          path: |
            model/model.tar.gz
            artifacts/metrics.json

      - name: Configure AWS credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::923357842396:role/GitHubActionsRole
          aws-region: ap-south-1

      - name: Verify AWS identity
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          aws sts get-caller-identity

      - name: Upload model to S3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          aws s3 cp model/model.tar.gz s3://sagemaker-mlops-project-artifacts/models/churn/${{ github.sha }}/model.tar.gz

      - name: Install deployment dependencies
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          pip install -r requirements-deploy.txt

      - name: Deploy, test and cleanup SageMaker
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          SAGEMAKER_EXECUTION_ROLE_ARN: ${{ vars.SAGEMAKER_EXECUTION_ROLE_ARN }}
        run: |
          python scripts/deploy_sagemaker.py